dist: xenial
sudo: required
services:
- docker
script:
- docker build -t atomicdex_docs_image .
- docker run --rm -v $(pwd):/app/ -w /app/ -u $(id -u):$(id -g) atomicdex_docs_image
- cd docs/.vuepress/dist/
- echo 'developers.atomicdex.io' > CNAME
deploy:
- provider: pages
  skip-cleanup: true
  github-token: "$GH_TOKEN"
  local-dir: docs/.vuepress/dist/
  repo: komodoplatform/AtomicDEX-docs
  on:
    branch: master
branches:
  only:
  - master
