language: node_js
node_js:
  - lts/*
install:
  - yarn install
script:
  - ./algolia-key.sh
  - yarn docs:build
  - echo 'developers.atomicdex.io' > docs/.vuepress/dist/CNAME
deploy:
  - provider: pages
    skip-cleanup: true
    github-token: "$GH_TOKEN"
    local-dir: docs/.vuepress/dist/
    repo: komodoplatform/AtomicDEX-docs
    on:
      branch: master
branches:
  only:
    - master
